### ISSUE TITLE
Exception with retry or botocore

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#99]
```
root@ubuntu1604-JFrog:~/aws# kk logs neuvector-csp-pod-56ccccfb7b-trbm6
2023-05-19T20:59:47.117|INFO|CSPBillingAdapter|CSPBillingAdapter logging setup complete
2023-05-19T20:59:47.123|INFO|CSPBillingAdapter|Config loaded: {'version': '0.0.1', 'billing_interval': 'test', 'query_interval': 60, 'product_code': '8yq550xpepyhn6uq8f4pmwv6e', 'usage_metrics': {'managed_node_count': {'usage_aggregation': 'average', 'consumption_reporting': 'volume', 'minimum_consumption': 5, 'dimensions': [{'dimension': 'tier_1', 'min': 0, 'max': 15}, {'dimension': 'tier_2', 'min': 16, 'max': 50}, {'dimension': 'tier_3', 'min': 51, 'max': 100}, {'dimension': 'tier_4', 'min': 101, 'max': 250}, {'dimension': 'tier_5', 'min': 251, 'max': 1000}, {'dimension': 'tier_6', 'min': 1001}]}}, 'reporting_api_is_cumulative': False, 'reporting_interval': 60}
2023-05-19T20:59:47.123|INFO|CSPBillingAdapter|Loaded in cluster config.
2023-05-19T20:59:47.328|INFO|CSPBillingAdapter|Adapter setup complete
2023-05-19T20:59:47.685|ERROR|CSPBillingAdapter|Failed to meter bill: An error occurred (TimestampOutOfBoundsException) when calling the MeterUsage operation: Timestamp 2023-05-19T01:02:36Z is out of allowed range
2023-05-19T20:59:47.685|ERROR|CSPBillingAdapter|CSP Billing Adapter error: Fatal error while validating metering API access: catching classes that do not inherit from BaseException is not allowed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/csp_billing_adapter/utils.py", line 233, in retry_on_exception
    return func_call()
  File "/usr/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.6/site-packages/csp_billing_adapter_amazon/plugin.py", line 86, in meter_billing
    raise exc  # Re-raise exception to calling scope
  File "/usr/lib/python3.6/site-packages/csp_billing_adapter_amazon/plugin.py", line 74, in meter_billing
    DryRun=dry_run
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.TimestampOutOfBoundsException: An error occurred (TimestampOutOfBoundsException) when calling the MeterUsage operation: Timestamp 2023-05-19T01:02:36Z is out of allowed range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/csp_billing_adapter/adapter.py", line 299, in main
    func_name="hook.meter_billing"
  File "/usr/lib/python3.6/site-packages/csp_billing_adapter/utils.py", line 234, in retry_on_exception
    except exceptions as error:
TypeError: catching classes that do not inherit from BaseException is not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/csp_billing_adapter/adapter.py", line 311, in main
    f'Fatal error while validating metering API access: {error}'
csp_billing_adapter.exceptions.CSPBillingAdapterException: Fatal error while validating metering API access: catching classes that do not inherit from BaseException is not allowed
```

**Comment by rtamalin** [comment]
That error suggests an error in the arguments to a call to retry somewhere, where something other than the exception is passed as the first unnamed argument, becoming `exceptions` the exceptions argument...
